### PR TITLE
Use reboot instead of root

### PR DESCRIPTION
**Pull request by MartijnCuppens**

### CODE REVIEW

**Comment by Johann-S** [comment]
The `root` allow folks to customize the color of our components 😟 so without that they can't, so I'm not in favor of removing `root`, but you can add `reboot` for our components 👍

**Comment by MartijnCuppens** [comment]
`root` only adds some custom properties (css variables). It doesn't allow people to change the color of components (or am I missing something 😛).

**Comment by Johann-S** [comment]
Oh ok, so in which situation should we include `_root.scss` ?

**Comment by Johann-S** [comment]
Hmm I change the target branch but it did something wrong 🤔 it added commits which are already merged in master

**Comment by Johann-S** [comment]
>Oh ok, so in which situation should we include _root.scss ?

If you have some information about that @XhmikosR ?

**Comment by XhmikosR** [comment]
Root is only for CSS variables. It's a separate component. Reboot isn't optional and should always be included when any CSS is included.

**Comment by Johann-S** [comment]
Hmm ok I understand, but I don't know when we should add `_root.scss` and when we shouldn't add it 🤔

**Comment by XhmikosR** [comment]
It's a separate component. So only if its selected

**Comment by Johann-S** [comment]
@XhmikosR https://github.com/Johann-S/bs-customizer/commit/27ab82335f27960a70dc89636e4eb0f382b912ee 😉

**Comment by Johann-S** [comment]
Sorry @MartijnCuppens I did what you did... So I'll close this PR.

The things, is, Root isn't present in Bootstrap documentation so nobody knows, there is a Root component 😟

**Comment by XhmikosR** [comment]
Yeah because it was an experiment and might be removed at any time.

**Pull request closed without merging**
