### PR TITLE
Accessibility fixes.

### PR DESCRIPTION
**Pull request by XhmikosR**
Only @patrickhlauke can help us with this more :)

Basically a review of this patch and how we should handle the loader.

### CODE REVIEW

**Comment by patrickhlauke** [comment]
LGTM

**Comment by XhmikosR** [comment]
@patrickhlauke: thanks! How about the loader? https://github.com/Johann-S/bs-customizer/blob/master/src/dialog-loader.js#L22

**Comment by patrickhlauke** [comment]
i'd need to see it in action, but likely you'll want to have a look at something like the button in https://codepen.io/patrickhlauke/pen/dddMqO

**Comment by XhmikosR** [comment]
You can see it in action here https://johann-s.github.io/bs-customizer/, just choose a plugin and hit download :)

**Pull request merged**
