### PR TITLE
Add js prefix to elements where custom js is applied to

### LINKED ISSUE #40: Add js prefix to all elements where javascript is applied to.
In my own projects I always add a `js-` prefix to classes of element where javascript is applied to.
By using `js-` prefix for classes in DOM elements you decouple functional aspects of these elements from CSS ones. An example:

```html
<a class="btn js-popup">Click me!</a>
```

This has some advantages:
- as css coder, you can easily change anchor design by changing btn class and not worry it'll break pop up behavior.
- and conversely, as JavaScript developer you can remove popup behavior and never break any existing CSS rules.

(source: https://coderwall.com/p/qktuzw/decouple-javascript-classes-from-css-ones-by-using-prefix, this just perfectly described what I meant)

What do you think @Johann-S, @XhmikosR?

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Use classes with `.js-` prefix for elements where custom javascript is applied to.

Closes #40.

### CODE REVIEW

**Comment by XhmikosR** [comment]
IMO there's nothing wrong in using IDs in JS, and in fact it should be always faster.

**Comment by MartijnCuppens** [comment]
> IMO there's nothing wrong in using IDs in JS, and in fact it should be always faster.

I personally don't like to mix class and id selectors, but you have a point that they are slightly faster. @Johann-S, what do you think?

**Comment by Johann-S** [comment]
We have few elements in our index.html so our perf won't change a lot, and it it bother us a lot we can query our elements with native methods

**Comment by Johann-S** [comment]
Can you update your PR @MartijnCuppens ? And I'll merge it 👍

**Comment by MartijnCuppens** [comment]
Updated ;)

**Comment by XhmikosR** [comment]
@MartijnCuppens: that's not a rebase :P

**Comment by MartijnCuppens** [comment]
@XhmikosR does it matter if it's a merge or rebase?

**Comment by XhmikosR** [comment]
Definitely. In this case, it cannot be merged at all.

**Comment by MartijnCuppens** [comment]
@XhmikosR, I've rebased this PR.

**Comment by Johann-S** [comment]
Sorry @MartijnCuppens again an other rebase 😆 do not hesitate to merge your PR 😉

**Comment by XhmikosR** [comment]
@MartijnCuppens I had already rebased it, don't overwrite the branch.

**Comment by MartijnCuppens** [comment]
Ow, that was going on, sec I'll fix it

**Comment by XhmikosR** [comment]
It's already fixed :P

**Pull request merged**
