### PR TITLE
update to bootstrap v4.3.1

### PR DESCRIPTION
**Pull request by Johann-S**
~~To do after that update our deps~~

Fixes: #91

### CODE REVIEW

**Comment by XhmikosR** [comment]
Did you check the unminified output? I checked the minified one quickly and I see it's slightly smaller with some parts missing. I don't even remember if that was the case before too.

**Comment by Johann-S** [comment]
I'll take a second look thanks 👍

**Comment by Johann-S** [comment]
Now it should be ok @XhmikosR 

/CC @MartijnCuppens if you want to take a look

**Comment by XhmikosR** [comment]
Now the CSS is identical in size.

**Pull request merged**
