### PR TITLE
Build SASS files

### PR DESCRIPTION
**Pull request by Johann-S**
A lot to do here

Plugins:
 - [x] Alert
 - [x] Button
 - [x] Carousel
 - [x] Collapse
 - [x] Dropdown
 - [x] Modal
 - [x] Popover
 - [x] ScrollSpy
 - [x] Tab (Nav)
 - [x] Tooltip

Other tasks:
 - [x] Minify CSS generated

Other CSS parts:
 - [x] Badge
 - [x] Breadcrumb
 - [x] Card
 - [x] Code
 - [x] Custom form and Forms
 - [x] Images
 - [x] Input group
 - [x] Jumbotron
 - [x] List group
 - [x] Media
 - [x] Navs / Navbar
 - [x] Pagination
 - [x] Progress
 - [x] Reboot
 - [x] Tables
 - [x] Types
 - [x] Utilities

### CODE REVIEW

**Comment by XhmikosR** [comment]
Maybe we should split the bundle and make use of code splitting?

**Comment by Johann-S** [comment]
Will it load faster if we split our bundle in two files ?

**Comment by XhmikosR** [comment]
It's common practice to lazy load code and this is a huge file for sure.

https://webpack.js.org/guides/code-splitting/

**Comment by Johann-S** [comment]
Yep that's true, I'll work on that 👍

**Comment by Johann-S** [comment]
@MartijnCuppens if you can take a look to check if I'm not missing something about Bootstrap SCSS, thank you ❤️

**Comment by Johann-S** [comment]
@XhmikosR I added Netlify 😉

**Comment by Johann-S** [comment]
Everything is done here @XhmikosR and @MartijnCuppens so if you want to review it do not hesitate 😉 

But I'll merge that soon 😄

**Comment by Johann-S** [comment]
@MartijnCuppens you can see my branch in action here: https://deploy-preview-21--dreamy-montalcini-8976b2.netlify.com/

**Comment by MartijnCuppens** [comment]
Hmm, looks a bit messy like that, I'll see what I can do to improve that.

Apart from that, if I select the modal, I don't get the css for the modals,  is that intentional?

**Comment by Johann-S** [comment]
Maybe you have an error in your console, which checkboxs did you choose ?

Yep I have some ideas to improve the UI, for example we should put `Options` on the right and our Options should be available everytime

**Comment by Johann-S** [comment]
Oh ok I understand sorry 😆 

If you want to get the modal CSS, you have to check Modal in JavaScript plugins and check `Include JavaScript plugin CSS` 😉

**Comment by XhmikosR** [comment]
I will give it a go tomorrow and let you know.

**Comment by MartijnCuppens** [comment]
I don't think there is a need for the `Include JavaScript plugin CSS` checkbox. This should be enabled by default. I don't think there would be a situation where you want to include the modal js and some css but not the modal css.

What do you think?

**Comment by XhmikosR** [comment]
Yup, agreed. Should be enabled for sure.

**Comment by Johann-S** [comment]
So if the user choose just one JS plugin I should build the CSS part by default ? 

But I think there is a lack of user feedback, I'm more in favor of keeping this checkbox and checked that checkbox if one JS plugin is selected

**Comment by MartijnCuppens** [comment]
I understand, just leave it checked by default then.

Hmm, I was thinking: should we include the reboot if we only include the modal css? 🤔

**Comment by XhmikosR** [comment]
Yup,reboot should always be included when any css is included

**Comment by Johann-S** [comment]
I don't think so, we should just provide what the component needs to be built, and allow folks to choose to add things or not, that's what we have with this PR

**Comment by XhmikosR** [comment]
@Johann-S: the point of Reboot is to normalize, is not optional.

**Pull request merged**
